<div class="wrbda-table">
    <table class="table">
        <tr class="wr-label-table">
            <th> <input type="checkbox" id="check_all" name="check_all" onclick="wbloc_seleccionar()"> <?php _e('ID') ?></th>
            <th><?php _e('Enlaces') ?></th>
            <th><?php _e('Dirección Ip') ?></th>
            <th><?php _e('Ubicación') ?></th>
            <th><?php _e('fecha/hora') ?></th>
            <th><?php _e('Opción') ?></th>
        </tr>
        <?php

        if (!empty($lista_datos)) {
            foreach ($lista_datos as $key => $value) { ?>
                <tr>
                    <td><input type="checkbox" class="cbox1" id="cbox1[]" name="cbox1[]" value="<?= $value->id ?>"><?= $value->id ?></td>
                    <td><?= $value->site_url; ?></td>
                    <td><?= $value->direccion_ip; ?></td>
                    <td><?= $value->ubicacion; ?></td>
                    <td><?= $value->time; ?></td>
                    <td>
                        <div class="wrbda-th-opciones-slg">
                            <button class="wbloc_btn_delete" onclick="wbloc_delete_page('<?= $value->id ?>','<?= $pagina ?>')"><?php printf('Eliminar'); ?></i></button>
                        </div>
                    </td>
                </tr>
        <?php  }
        } else {
            echo "<tr><td class='text-center' colspan='7'>" . __('No ahy datos') . "</td></tr>";
        } ?>
    </table>
</div>



<?php
$diferencia = $paginas - $pagina;
$start_loop = $pagina;
if ($diferencia <= CANT_ITEMS_BY_PAGE) {
    $start_loop =   ($paginas - CANT_ITEMS_BY_PAGE);
}
$end_loop = $start_loop + (CANT_ITEMS_BY_PAGE); ?>
<nav>
    <div class="wr-paginacion">
        <ul class="pagination">
            <p>Pagina <?php echo $pagina ?> / <?php echo $paginas ?> de <?php echo $conteo ?> datos</p>
            <li class="page-item">
                <a onclick="wbloc_load_page('<?= 1; ?>','<?= $codigo; ?>','Realizado')">Inicio</a>
            </li>
            <?php if ($pagina > 1) { ?>
                <li class="page-item">
                    <a onclick="wbloc_load_page('<?php echo $pagina - 1 ?>','<?= $codigo; ?>','Realizado')">
                        <span aria-hidden="true">
                            << </span>
                    </a>
                </li>
            <?php } ?>
            <?php for ($i = $start_loop; $i <= $end_loop; $i++) { ?>
                <?php if ($i > 0) { ?>
                    <li class="<?php if ($i == $pagina) echo "active" ?>">
                        <a onclick="wbloc_load_page('<?php echo $i ?>','<?= $codigo; ?>','Realizado')">
                            <?php echo $i ?></a>
                    </li>
            <?php }
            } ?>
            <?php if ($pagina < $end_loop) {  ?>
                <li>
                    <a onclick="wbloc_load_page('<?php echo $pagina + 1 ?>','<?= $codigo; ?>','Realizado')">
                        <span aria-hidden="true">>></span>
                    </a>
                </li>
                <li class="page-item">
                    <a onclick="wbloc_load_page('<?= $paginas; ?>','<?= $codigo; ?>','Realizado')">Ultima</a>
                </li>
            <?php } ?>
        </ul>
    </div>
</nav>